version: '3.10'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile.gpu
    image: translation_docker_api:latest  
    volumes:
      - .:/app
      - $HOME/.cache/pip:/root/.cache/pip  # Mount the pip cache
    ports:
      - "5001:5001"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: production
    command: gunicorn --bind 0.0.0.0:5001 app:app
