name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker image tag
        run: echo "IMAGE_TAG=mohammedhamdy98/ttst-fastapi-docker:$(date +%s)" >> $GITHUB_ENV

      - name: List files to ensure Dockerfile exists
        run: ls -la

      - name: Build the Docker image
        run: |
          docker buildx build \
          --file dockerfile.gpu \
          --tag mohammedhamdy98/ttst-fastapi-docker:$(date +%s) \
          --build-arg PYTHON_VERSION=3.10 \
          --build-arg DEBIAN_FRONTEND=noninteractive \
          --build-arg PIP_NO_CACHE_DIR=1 \
          --cache-from=type=registry,ref=mohammedhamdy98/ttst-fastapi-docker:cache \
          --cache-to=type=registry,ref=mohammedhamdy98/ttst-fastapi-docker:cache,mode=max \
          --push .  # This is the context path, ensuring Docker looks in the current directory for the Dockerfile
