name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker image tag
        run: echo "IMAGE_TAG=mohammedhamdy98/ttst-fastapi-docker:$(date +%s)" >> $GITHUB_ENV

      - name: List files to ensure Dockerfile exists
        run: ls -la

      - name: Build the Docker image
        run: |
          docker buildx build \
            --file dockerfile.gpu \  # Ensure the correct path to the Dockerfile
            --tag ${{ env.IMAGE_TAG }} \
            --build-arg PYTHON_VERSION=3.10 \
            --build-arg DEBIAN_FRONTEND=noninteractive \
            --build-arg PIP_NO_CACHE_DIR=1 \  # Disable pip caching to save space
            --cache-from=type=registry,ref=mohammedhamdy98/ttst-fastapi-docker:cache \
            --cache-to=type=registry,ref=mohammedhamdy98/ttst-fastapi-docker:cache,mode=max \
            --push dockerfiles/.  # Ensure build context is correct (current directory)
